#!/usr/bin/env bash
# running as the nginx user
pkill "apache2"
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/g" /etc/nginx/sites-available/default
sudo -u service nginx start
